project_id = "vpehklrzzgklskapnfmk"

[functions.process-audiobook-metadata]
verify_jwt = false

[functions.generate-audiobook-cover]
verify_jwt = false

[functions.get-audiobook-presigned-url]
verify_jwt = true